######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 25 11:35:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
FORMS += imageViewer.ui

# Input
HEADERS += dropArea.h dropSiteWindow.h
SOURCES += dropArea.cpp dropSiteWindow.cpp main.cpp
